In [23]:
import numpy as np
V = [0,1,3,5,9]
W = [0,2,3,4,7]
n = 4
b = 10
F = np.zeros((n+1, b+1))
i = np.zeros((n+1,b+1))

In [24]:
for k in range(1, n+1):
    for y in range(1, b+1):
        if k == 1:
            F[k][y] = y//W[k] * V[k]
        else:
            for yy in range(y//W[k]+1):
                vy = y - yy * W[k]
                if vy >= 0:
                    F[k][y] = max(F[k-1][y], F[k-1][vy]+yy * V[k])
                    i[k][y] = yy
                elif vy < 0 :
                    F[k][y] = F[k-1][y]    
                    i[k][y] = yy
        
print(F)
print(i)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  1.  2.  2.  3.  3.  4.  4.  5.]
 [ 0.  0.  1.  3.  3.  4.  6.  6.  7.  9.  9.]
 [ 0.  0.  1.  3.  5.  5.  6.  8. 10. 10. 11.]
 [ 0.  0.  1.  3.  5.  5.  6.  9. 10. 10. 12.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 2. 2. 2. 3. 3.]
 [0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]]
